# Generated by Django 3.0.8 on 2020-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfsearcherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
